//
//  SocketCommandID.h
//  youwo
//
//  Created by mygame on 15/1/30.
//  Copyright (c) 2015年 mygame. All rights reserved.
//

#ifndef youwo_SocketCommandID_h
#define youwo_SocketCommandID_h
enum {
    // 网络错误标志
    kNetworkIsUnreachable                                   = -1,// 网络不给力
    kReconnectServer                                        = -2,// 需要重新连接服务器
    kOperationTimeout                                       = -3,// 网络超时


    // 协议命令标志
    kCMD_HEARTBEAT_REQ = 1, // 心跳请求
    kCMD_HEARTBEAT_RESP = 2, // 心跳请求返回
    kCMD_KICKOFF_USER_NOTIFY = 3, // 服务器踢掉用户通知给客户端
    kCMD_VC_CODE_REQ = 1003, // 注册验证码请求
    kCMD_VC_CODE_RESP = 1004, // 注册验证码请求返回
    kCMD_REGISTER_REQ = 1005, // 注册账号请求
    kCMD_REGISTER_RESP = 1006, // 注册账号返回
    kCMD_NAME_LOGON_REQ = 1007, // 用户名登录请求
    kCMD_NAME_LOGON_RESP = 1008, // 用户名登录返回
    kCMD_BASE_INFO_REQ = 1009, // 用户基本信息请求
    kCMD_BASE_INFO_RESP = 1010, // 用户基本信息应答
    kCMD_UPDATE_BASE_INFO_REQ = 1011, // 用户更新基本信息请求
    kCMD_UPDATE_BASE_INFO_RESP = 1012, // 用户基更新本信息应答
    kCMD_BASE_INFO_LIST_REQ = 1013, // 用户批量请求基本信息
    kCMD_BASE_INFO_LIST_RESP = 1014, // 用户批量请求基本信息应答
    kCMD_UPDATE_BIRTHDAY_REQ = 1015, // 用户更新出生日期
    kCMD_UPDATE_BIRTHDAY_RESP = 1016, // 用户更新出生日期应答
    kCMD_UPDATE_NICKNAME_REQ = 1017, // 用户更新昵称
    kCMD_UPDATE_NICKNAME_RESP = 1018, // 用户更新昵称应答
    kCMD_UPDATE_OCCUPATION_REQ = 1019, // 用户更新职业
    kCMD_UPDATE_OCCUPATION_RESP = 1020, // 用户更新职业应答
    kCMD_UPDATE_RESIDENTION_REQ = 1021, // 用户更新居住地
    kCMD_UPDATE_RESIDENTION_RESP = 1022, // 用户更新居住地应答
    kCMD_UPDATE_SIGNATURE_REQ = 1023, // 用户更新个性签名
    kCMD_UPDATE_SIGNATURE_RESP = 1024, // 用户更新个性签名应答
    kCMD_UPDATE_PORTRAIT_REQ = 1025, // 用户更新头像
    kCMD_UPDATE_PORTRAIT_RESP = 1026, // 用户更新头像应答
    kCMD_UPDATE_GENDER_REQ = 1027, // 用户更新性别
    kCMD_UPDATE_GENDER_RESP = 1028, // 用户更新性别应答
    kCMD_USER_ACCOUNT_INFO_REQ = 1029, // 用户账户信息请求
    kCMD_USER_ACCOUNT_INFO_RESP = 1030, // 用户账户信息应答
    kCMD_CG_UPDATE_RESIDENTION_DETAIL_REQ = 1031, // 用户更新居住地详细信息
    kCMD_GC_UPDATE_RESIDENTION_DETAIL_RESP = 1032, // 用户更新居住地详细信息应答
    kCMD_CLIENT_PHONE_QUERY_USERID_REQ = 1033, // 根据手机号请求uid
    kCMD_CLIENT_PHONE_QUERY_USERID_RESP = 1034, // 根据手机号请求uid响应
    kCMD_RETRIEVE_CODE_REQ = 1035, // 获取修改密码手机验证码请求
    kCMD_RETRIEVE_CODE_RESP = 1036, // 获取修改密码手机验证码响应
    kCMD_VALIDATE_RETRIEVE_CODE_REQ = 1037, // 验证获取的手机验证码请求
    kCMD_VALIDATE_RETRIEVE_CODE_RESP = 1038, // 验证获取的手机验证码请求响应
    kCMD_MODIFY_PASSWORD_REQ = 1039, // 修改密码请求
    kCMD_MODIFY_PASSWORD_RESP = 1040, // 修改密码响应
    kCMD_TOKEN_LOGON_REQ = 1041, // Token登陆请求
    kCMD_TOKEN_LOGON_RESP = 1042, // Token登陆响应
    kCMD_ACCOUNT_INFO_LIST_REQ = 1043, // 用户批量请求账户信息
    kCMD_ACCOUNT_INFO_LIST_RESP = 1044, // 用户批量请求账户信息应答
    kCMD_ADDRESS_PHONE_QUERY_REQ = 1045, // 用户批量请求手机号码对应的uid
    kCMD_ADDRESS_PHONE_QUERY_RESP = 1046, // 用户批量请求手机号码对应的uid响应
    kCLIENT_REQUEST_ACCESS_NAME_LOGIN = 1047, // 用户名密码登录请求
    kCLIENT_REQUEST_ACCESS_TOKEN_LOGIN = 1048, // token登录请求
    kACCESS_RESPONSE_CLIENT_NAME_LOGIN = 1049, // 用户名密码登录应答
    kCLIENT_REQUEST_ACCESS_TRADE_MIN = 2000, // 客户端请求网关交易服务器最小协议号(不包含本身)
    kCLIENT_REQUEST_ACCESS_TRADE_CREATE_ORDER = 2007, // 客户端请求网关交易服务器创建订单
    kTRADE_RSPONSE_ACCESS_CLIENT_CREATE_ORDER = 2008, // 交易服务器回应网关客户端创建订单
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_ORDER_BASIC_INFO = 2009, // 客户端请求网关交易服务器查询订单基本信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_ORDER_BASIC_INFO = 2010, // 交易服务器回应网关客户端查询订单基本信息
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_ORDER_SPECIFIC_INFO = 2011, // 客户端请求网关交易服务器查询订单详细信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_ORDER_SPECIFIC_INFO = 2012, // 交易服务器回应网关客户端查询订单详细信息
    kCLIENT_REQUEST_ACCESS_TRADE_APPLY_ORDER = 2013, // 客户端请求网关交易服务器报名参与活动
    kTRADE_RSPONSE_ACCESS_CLIENT_APPLY_ORDER = 2014, // 交易服务器回应网关客户端报名参与活动
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_APPLYER = 2015, // 客户端请求网关交易服务器选择参与对象
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_APPLYER = 2016, // 交易服务器回应网关客户端选择参与对象
    kCLIENT_CONFIRM_OR_CANCEL_ORDER_REQ = 2017, // 客户端确认订单或者取消订单 请求
    kCLIENT_CONFIRM_OR_CANCEL_ORDER_RESP = 2018, // 客户端确认订单或者取消订单 服务器响应
    kCLIENT_CREATED_ORDER_BRIEF_REQ = 2019, // 客户端查询创建过的订单 请求
    kCLIENT_CREATED_ORDER_BRIEF_RESP = 2020, // 客户端查询创建过的订单 应答
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_DISCUSS = 2021, // 客户端请求网关交易服务器查看评论信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_DISCUSS = 2022, // 交易服务器回应网关客户端查看评论信息
    kCLIENT_REQUEST_ACCESS_TRADE_CREATE_DISCUSS = 2023, // 客户端请求网关交易服务器发表评论
    kTRADE_RSPONSE_ACCESS_CLIENT_CREATE_DISCUSS = 2024, // 交易服务器回应网关客户端发表评论
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_PHOTO_WALL = 2025, // 客户端请求网关交易服务器获取照片墙信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_PHOTO_WALL = 2026, // 交易服务器回应网关客户端获取照片墙信息
    kCLIENT_REQUEST_ACCESS_TRADE_UPDATE_PHOTO_WALL = 2027, // 客户端请求网关交易服务器更新照片墙信息
    kTRADE_RSPONSE_ACCESS_CLIENT_UPDATE_PHOTO_WALL = 2028, // 交易服务器回应网关客户端更新照片墙信息
    kCLIENT_REQUEST_ACCESS_TRADE_REGISTER_TRADEINFO = 2029, // 客户端请求网关交易服务器注册账号交易信息
    kTRADE_RSPONSE_ACCESS_CLIENT_REGISTER_TRADEINFO = 2030, // 交易服务器回应网关客户端注册账号交易信息
    kCLIENT_REQUEST_ACCESS_TRADE_UPDATE_ARGUE = 2031, // 客户端请求网关交易服务器对订单进行评价
    kTRADE_RSPONSE_ACCESS_CLIENT_UPDATE_ARGUE = 2032, // 交易服务器回应网关客户端对订单进行评价
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_TRADEUSERINFO = 2033, // 客户端请求网关交易服务器查询账号交易信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_TRADEUSERINFO = 2034, // 交易服务器回应网关客户端查询账号交易信息
    kCLIENT_REQUEST_ACCESS_TRADE_UPDATE_SERVICE = 2035, // 客户端请求网关交易服务器更新我的服务
    kTRADE_RSPONSE_ACCESS_CLIENT_UPDATE_SERVICE = 2036, // 交易服务器回应网关客户端更新我的服务
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_GIFTS = 2037, // 客户端请求网关交易服务器查看礼物信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_GIFTS = 2038, // 交易服务器回应网关客户端查看礼物信息
    kCLIENT_REQUEST_ACCESS_TRADE_PRESENT_GIFTS = 2039, // 客户端请求网关交易服务器赠送礼物
    kTRADE_RSPONSE_ACCESS_CLIENT_PRESENT_GIFTS = 2040, // 交易服务器回应网关客户端赠送礼物
    kCMD_CT_BUY_CAR_REQ = 2041, // 买车
    kCMD_TC_BUY_CAR_RESP = 2042, // 买车响应
    kCMD_CT_OPERATE_CAR_REQ = 2043, // 操作车
    kCMD_TC_OPERATE_CAR_RESP = 2044, // 操作车响应
    kCT_APPLY_ORDER_BRIEF_REQ = 2045, // 客户端请求订单服务器 申请过的订单简要信息
    kTC_APPLY_ORDER_BRIEF_RESP = 2046, // 订单服务器响应 客户端 申请过的订单简要信息
    kCMD_CT_GUARANTEE_FRIEND_REQ = 2047, // 客户端请求担保好友
    kCMD_TC_GUARANTEE_FRIEND_RESP = 2048, // 客户端请求担保好友响应
    kCMD_CT_CANCEL_GUARANTEE_FRIEND_REQ = 2049, // 客户端请求取消担保好友
    kCMD_TC_CANCEL_GUARANTEE_FRIEND_RESP = 2050, // 客户端请求取消担保好友响应
    kCMD_CT_QUERY_GUARANTEE_FRIEND_REQ = 2051, // 客户端请求查询担保好友
    kCMD_TC_QUERY_GUARANTEE_FRIEND_RESP = 2052, // 客户端请求查询担保好友响应
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_TASKINFO = 2053, // 客户端请求网关交易服务器查询任务信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_TASKINFO = 2054, // 交易服务器回应网关客户端查询任务信息
    kCLIENT_REQUEST_ACCESS_TRADE_SELL_GIFTS = 2055, // 客户端请求网关交易服务器出售礼物
    kTRADE_RSPONSE_ACCESS_CLIENT_SELL_GIFTS = 2056, // 交易服务器回应网关客户端出售礼物
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_USERINFOLIST = 2057, // 客户端请求网关交易服务器查询多人账号交易信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_USERINFOLIST = 2058, // 交易服务器回应网关客户端查询多人账号交易信息
    kCLIENT_REQUEST_ACCESS_TRADE_UPLEVEL_VIP = 2059, // 客户端请求网关交易服务器升级vip等级
    kTRADE_RSPONSE_ACCESS_CLIENT_UPLEVEL_VIP = 2060, // 交易服务器回应网关客户端升级vip等级
    kCLIENT_REQUEST_ACCESS_TRADE_GET_CHATROOMINFOLIST = 2061, // 客户端请求网关交易服务器获取当前火热聊天室信息列表
    kTRADE_RSPONSE_ACCESS_CLIENT_GET_CHATROOMINFOLIST = 2062, // 交易服务器回应网关客户端获取当前火热聊天室信息列表
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_GIFTSPAGIDLIST = 2063, // 客户端请求网关交易服务器查询礼物页ID列表
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_GIFTSPAGIDLIST = 2064, // 交易服务器回应网关客户端查询礼物页ID列表
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_IDENTITYBANK = 2065, // 客户端请求网关交易服务器查询身份证银行卡信息
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_IDENTITYBANK = 2066, // 交易服务器回应网关客户端查询身份证银行卡信息
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_VISITORSLIST = 2067, // 客户端请求网关交易服务器查询最近访问列表
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_VISITORSLIST = 2068, // 交易服务器回应网关客户端查询最近访问列表
    kCMD_CT_QUERY_SELF_GUARANTEE_REQ = 2069, // 客户端请求 自己担保的人
    kCMD_TC_QUERY_SELF_GUARANTEE_RESP = 2070, // 客户端请求 自己担保的人响应
    kCMD_CT_QUERY_PROMISE_SELF_REQ = 2071, // 客户端请求查询 担保自己的人
    kCMD_TC_QUERY_PROMISE_SELF_RESP = 2072, // 客户端请求查询担保自己的人响应
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_PARTICULARS = 2073, // 客户端请求网关交易服务器查询详细描述
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_PARTICULARS = 2074, // 交易服务器回应网关客户端查询详细描述
    kCMD_CT_ORDER_STATE_INFO_LIST_REQ = 2075, // 客户端请求交易服务器批量查询订单状态信息
    kCMD_TC_ORDER_STATE_INFO_LIST_RESP = 2076, // 交易服务器回应客户端查询结果
    kCMD_CT_USER_COMPLAINT_REQ = 2077, // 投诉请求
    kCMD_TC_USER_COMPLAINT_RESP = 2078, // 投诉请求响应
    kCLIENT_REQUEST_ACCESS_TRADE_ORDER_DONE = 2079, // 客户端请求网关交易服务器完成订单
    kTRADE_RSPONSE_ACCESS_CLIENT_ORDER_DONE = 2080, // 交易服务器回应网关客户端完成订单
    kCLIENT_REQUEST_ACCESS_TRADE_ORDER_CLOSEDOWN = 2081, // 客户端请求网关交易服务器关闭订单
    kTRADE_RSPONSE_ACCESS_CLIENT_ORDER_CLOSEDOWN = 2082, // 交易服务器回应网关客户端关闭订单
    kCMD_AT_ONLINE_USER_COUNT = 2083, // 网关通知交易服务器在线人数
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_APPLYERUSERINFOLIST = 2084, // 客户端请求网关交易服务器查询报名者信息列表
    kTRADE_RSPONSE_ACCESS_CLIENT_SELECT_APPLYERUSERINFOLIST = 2085, // 交易服务器回应网关客户端查询报名者信息列表
    kCLIENT_NOTIFY_TRADE_USER_GIS_INFO = 2087, // 客户端通知交易服务器用户的地理位置信息，更新到LBS
    kTRADE_RSPONSE_CLIENT_USER_GIS_INFO = 2088, // 交易服务器回应客户端更新用户的地理位置信息结果
    kCMD_CT_HOME_ORDER_INFO_REQ = 2089, // 首页订单信息请求
    kCMD_TC_HOME_ORDER_INFO_RESP = 2090, // 首页订单信息响应
    kCLIENT_REQUEST_ACCESS_TRADE_SELECT_ORDER_DETAILS_INFO = 2091, // 客户端请求网关交易服务器查询订单详细信息(合并界面协议)
    kTRADE_RESPONSE_ACCESS_CLIENT_SELECT_ORDER_DETAILS_INFO = 2092, // 交易服务器回应网关客户端查询订单详细信息(合并界面协议)
    kCLIENT_REQUEST_ACCESS_TRADE_COMPILE_USER_INFO = 2093, // 客户端请求网关交易服务器编辑资料
    kTRADE_RESPONSE_ACCESS_CLIENT_COMPILE_USER_INFO = 2094, // 交易服务器回应网关客户端编辑资料
    kCMD_CT_GLOBAL_USER_INFO_REQ = 2097, // 全局用户信息请求
    kCMD_TC_GLOBAL_USER_INFO_RESP = 2098, // 全局用户信息响应
    kCLIENT_REQUEST_ACCESS_TRADE_GET_TASK_AWARD = 2101, // 客户端请求网关交易服务器获取任务奖励
    kTRADE_RESPONSE_ACCESS_CLIENT_GET_TASK_AWARD = 2102, // 交易服务器回应网关客户端获取任务奖励
    kCMD_SYSTEM_SEND_MESG = 2104, // 系统发送消息
    kCMD_CT_QUERY_DISCUSS_DETAIL_REQ = 2105, // 查询评论信息
    kCMD_TC_QUERY_DISCUSS_DETAIL_RESP = 2106, // 查询评论信息响应
    kCMD_CT_DELETE_DISCUSS_DETAIL_REQ = 2107, // 删除评论请求
    kCMD_TC_DELETE_DISCUSS_DETAIL_RESP = 2108, // 删除评论响应
    kCMD_CT_DISCUSS_ORDER_REQ = 2109, // 发表评论请求
    kCMD_TC_DISCUSS_ORDER_RESP = 2110, // 发表评论响应
    kCLIENT_REQUEST_ACCESS_TRADE_ORDER_DONE_APPLYER = 2111, // 客户端请求网关交易服务器接单人完成订单
    kTRADE_RESPONSE_ACCESS_CLIENT_ORDER_DONE_APPLYER = 2112, // 交易服务器回应网关客户端接单人完成订单
    kCLIENT_REQUEST_ACCESS_TRADE_ORDER_DONE_CREATER = 2113, // 客户端请求网关交易服务器发单人完成订单
    kTRADE_RESPONSE_ACCESS_CLIENT_ORDER_DONE_CREATER = 2114, // 交易服务器回应网关客户端发单人完成订单
    kCMD_CT_REPORT_INFO_REQ = 2115, // 举报请求
    kCMD_TC_REPORT_INFO_RESP = 2116, // 举报响应
    kCLIENT_REQUEST_ACCESS_TRADE_MAX = 3000, // 客户端请求网关交易服务器最大协议号(不包含本身)
    kCMD_CHAT_LOGON_REQ = 3001, // 用户登录聊天服务器请求
    kCMD_CHAT_LOGON_RESP = 3002, // 用户登录聊天服务器返回
    kCMD_CHAT_SEND_MSG_REQ = 3003, // 用户发聊天消息请求
    kCMD_CHAT_SEND_MSG_RESP = 3004, // 用户发聊天消息返回
    kCMD_CHATSVR_FORWARD_MSG = 3005, // 聊天服务器转发聊天消息
//    kCMD_ADD_FRIEND_REQ = 3007, // 用户添加好友请求       已经废弃
//    kCMD_ADD_FRIEND_RESP = 3008, // 用户添加好友应答      已经废弃
//    kCMD_DELETE_FRIEND_REQ = 3009, // 用户删除好友请求    已经废弃
//    kCMD_DELETE_FRIEND_RESP = 3010, // 用户删除好友应答   已经废弃
    kCMD_JOIN_GROUP_REQ = 3011, // 用户加入群请求
    kCMD_JOIN_GROUP_RESP = 3012, // 用户加入群应答
    kCMD_SECEDE_GROUP_REQ = 3013, // 用户退出群请求
    kCMD_SECEDE_GROUP_RESP = 3014, // 用户退出群应答
    kCLIENT_GET_THIRDPARTY_PAY_TOKEN_REQ = 4001, // 客户端请求获取第三方支付token
    kCLIENT_GET_THIRDPARTY_PAY_TOKEN_RESP = 4002, // 网关回应 客户端请求获取第三方支付token
    kCLIENT_GENERATE_PAY_ORDER_REQ = 4003, // 生成支付订单 请求
    kCLIENT_GENERATE_PAY_ORDER_RESP = 4004, // 生成支付订单 响应
    kTRADE_NOTIFY_CLIENT_PAY_RESULT = 4006, // 通知支付结果给客户端
    kCLIENT_EXCHANGE_STONE_OR_CURRENCY_REQ = 4007, // 客户端请求用有我币兑换游戏币或者试金石 请求
    kCLIENT_EXCHANGE_STONE_OR_CURRENCY_RESP = 4008, // 客户端请求用有我币兑换游戏币或者试金石 响应
    kCLIENT_WITHDRAW_HONESTY_GOLD_REQ = 4009, // 客户端请求提取诚信金 请求
    kCLIENT_WITHDRAW_HONESTY_GOLD_RESP = 4010, // 客户端请求提取诚信金 响应
    kCMD_PLAYERS_NEARBY_REQ = 2117, // 附近的人请求
    kCMD_PLAYERS_NEARBY_RESP = 2118, // 附近的人响应
    kCLIENT_REQUEST_ACCESS_TRADE_MAKE_REPUTATION = 2119, // 客户端请求网关交易服务器给某人点赞
    kTRADE_RESPONSE_ACCESS_CLIENT_MAKE_REPUTATION = 2120, // 交易服务器回应网关客户端给某人点赞
};

#endif
