/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 2cf24d0046363badc4b95a8c906bab49 */

/* creation time: Tue Sep  8 14:12:09 2015 */
/* tdr version: 2.6.3, build at 20150209 */

#ifndef _access_svr_metalib_h_
#define _access_svr_metalib_h_

namespace access_svr
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 1;
        }

        static const char* getName()
        {
            return "access_svr";
        }

        static const char* getMd5Sum()
        {
            return "2cf24d0046363badc4b95a8c906bab49";
        }

        static const char* getTdrVersion()
        {
            return "2.6.3, build at 20150209";
        }
};


}
#endif
