/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 2 */
/* metalib md5sum: 0822406026b27bb2b88868677cc8d59f */

/* creation time: Fri Sep 11 10:17:39 2015 */
/* tdr version: 2.6.3, build at 20150209 */

#ifndef _client_metalib_h_
#define _client_metalib_h_

namespace client
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 2;
        }

        static const char* getName()
        {
            return "client";
        }

        static const char* getMd5Sum()
        {
            return "0822406026b27bb2b88868677cc8d59f";
        }

        static const char* getTdrVersion()
        {
            return "2.6.3, build at 20150209";
        }
};


}
#endif
