/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: ac06d92e79273fda6e9b94d69e957a63 */

/* creation time: Mon Nov  3 18:11:20 2014 */
/* tdr version: 2.6.3, build at 20130820 */

#ifndef _public_define_h_
#define _public_define_h_

#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrBufUtil.h"
#include "TdrTypeUtil.h"


using tsf4g_tdr::TdrError;
using tsf4g_tdr::TdrReadBuf;
using tsf4g_tdr::TdrWriteBuf;

namespace access_svr
{


enum
{
    ACCESS_MAX_BODY_LEN = 4096, // 最大网络包
    ACCESS_MAX_MESSAGE_LEN = 128, // 最大消息长度
    ACCESS_TOKEN_LEN = 8, // Token长度
    LOBBY_PROTO_TYPE = 1, // 与大厅通信协议类型
    SESSION_MAX_LEN = 512, // SESSION最大长度
    USER_MAX_NODE = 300, // 用户节点最大数
    MAX_USER_LIST = 512, // 广播用户列表最大个数
};


enum AccessLobbyCmds
{
    ACCESS_LOBYY_NET_HEART_BEAT_REQUEST = 1, // 大厅和网关之间的心跳
    LOBYY_ACCESS_NET_HEART_BEAT_RESPONSE = 2, // 网关和大厅之间的心跳
    LOBBY_ACCESS_REGISTER_CMD_REQUEST = 3, // 大厅注册请求
    ACCESS_LOBBY_REGISTER_CMD_RESPONSE = 4, // 大厅注册返回
    LOBBY_ACCESS_SERVICE_STATUS_REQUEST = 5, // 大厅服务状态请求
    ACCESS_LOBBY_SERVICE_STATUS_RESPONSE = 6, // 大厅服务状态返回
    ACCESS_LOBBY_USER_LOGIN_CMD_REQUEST = 7, // 用户登录请求（网关至大厅）
    LOBBY_ACCESS_USER_LOGIN_CMD_RESPONSE = 8, // 用户登录返回(大厅至网关)
    ACCESS_LOBBY_COMM_CMD_REQUEST = 9, // 通用数据请求
    LOBBY_ACCESS_COMM_CMD_RSPONSE = 10, // 通用数据返回
    LOBBY_ACESS_CUR_PEOPLES_REFORM = 11, // 大厅当前人数通知
    ACCESS_LOBBY_REREGISTER_REQ = 12, // 要求重新注册请求（网关至大厅）
    ACCESS_LOBBY_USER_STATUS = 13, // 网关通知大厅用户状态（网关至大厅）
    LOBBY_ACCESS_LOGIN_OTHER = 14, // 大厅通知网关异地登陆（大厅至网关）
    ACCESS_LOBBY_ONLINE_USER = 15, // 网关通知大厅在线用户（网关至大厅）
    LOBBY_ACCESS_BROADCAST = 16, // 大厅给网关的用户广播包
    LOBBY_ACCESS_SEND_MSG_REQ = 17, // 大厅向网关发送消息请求（大厅至网关）
    ACCESS_LOBBY_SEND_MSG_RESP = 18, // 网关向大厅转发消息（网关至大厅）
};


enum AccessCmds
{
    GAS_API_INVALID_COMMAND = -1, // 无效请求命令字
    GAS_DIR_HEARTBEAT_REQUEST = 0, // 客户端和gas_dir之间的心跳
    GAS_DIR_HEARTBEAT_RESPONSE = 1, // gas_dir和客户端之间的心跳
    GAS_DIR_GETACCESS_REQUEST = 2, // 客户端从dir获取接入点
    GAS_DIR_GETACCESS_RESPONSE = 3, // dir返回接入点结果
    GAS_API_HEARTBEAT_REQUEST = 4097, // 客户端心跳请求
    GAS_API_HEARTBEAT_RESPONSE = 4098, // 客户端心跳响应
    GAS_API_SIGNUP_REQUEST = 4099, // 客户端鉴权请求
    GAS_API_SIGNUP_RESPONSE = 4100, // 客户端鉴权响应
};


}
#endif
